# Generated by Django 3.2.5 on 2022-02-24 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20220224_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie_title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
