# Generated by Django 3.2.5 on 2022-02-24 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_post_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
